-- МЯТА PLATINUM СПАРТАК: актуальные данные меню для v24.
-- Порядок: schema.sql → upgrade-v22.sql → seed.sql → make-admin.sql.

insert into public.venue_settings (id, venue_name, address, phone, hours) values
(1,'МЯТА PLATINUM СПАРТАК','Волоколамское ш., 71, корп. 1','+7 (985) 006-62-61','пн-чт 12:00-01:00, пт 12:00-02:00, сб 14:00-02:00, вс 14:00-01:00')
on conflict (id) do update set venue_name=excluded.venue_name,address=excluded.address,phone=excluded.phone,hours=excluded.hours;

insert into public.menu_sections(section_id,type,title,note,parent_group,sort_order,visible) values
('napitki','bar','Напитки','Безалкогольные напитки и лимонады','',0,true),
('chaynaya-karta','bar','Чайная карта','Классические чайные позиции','',10,true),
('kitayskie-chai','bar','Китайские чаи','Подборка китайских чаёв','',20,true),
('dobavki-k-chayu','bar','Добавки к чаю','Лимон, мята, мёд и другие добавки','',30,true),
('nechaynyy-chay','bar','Нечайный чай','Фруктовые и согревающие чайные миксы','',40,true),
('kofe','bar','Кофе','Кофейная классика','',50,true),
('pivo-i-sidr','bar','Пиво и сидр','Пиво, сидр и пивные позиции','',60,true),
('beloe-vino','bar','Белое вино','Подача по бокалам и бутылкам','',70,true),
('krasnoe-vino','bar','Красное вино','Подача по бокалам и бутылкам','',80,true),
('igristye-vina','bar','Игристые вина','Игристые вина по бокалам и бутылкам','',90,true),
('viski','bar','Виски','Крепкий алкоголь','',100,true),
('vodka','bar','Водка','Крепкий алкоголь','',110,true),
('nastoyki','bar','Настойки','Фирменные и классические настойки','',120,true),
('dzhin','bar','Джин','Крепкий алкоголь','',130,true),
('rom','bar','Ром','Крепкий алкоголь','',140,true),
('konyak','bar','Коньяк','Крепкий алкоголь','',150,true),
('tekila','bar','Текила','Крепкий алкоголь','',160,true),
('bitter','bar','Биттер','Крепкий алкоголь','',170,true),
('vermut','bar','Вермут','Крепкий алкоголь','',180,true),
('kokteyli','bar','Коктейли','Классические и фирменные коктейли','',190,true),
('zakuski','bar','Закуски','Закуски к напиткам','',200,true),
('pitstsa','bar','Пицца','Пицца','',210,true),
('deserty','bar','Десерты','Десерты','',220,true),
('dopolnitelnye-uslugi','bar','Дополнительные услуги','Дополнительные услуги и аренда','',230,true),
('hookah','hookah','Кальяны','Кальянная карта','',1000,true)
on conflict(section_id) do update set type=excluded.type,title=excluded.title,note=excluded.note,sort_order=excluded.sort_order,visible=excluded.visible;

insert into public.menu_items (item_key,type,section_id,section_title,name,description,volume,price,image_url,available,sort_order,archived,badge) values
('bar:napitki:coca-cola','bar','napitki','Напитки','Coca-Cola','Coca-Cola – один из самых популярных безалкогольных напитков в истории, а также один из наиболее узнаваемых брендов в мире.','',400,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vdsiob-uwa-mhgrmxshtn-bJyfNUtvqeanSd3ykb-9W.jpg',true,0,false,''),
('bar:napitki:coca-cola-zero','bar','napitki','Напитки','Coca-Cola zero','Coca-Cola Zero – это возможность насладиться удивительно освежающим вкусом классической Coca-Cola, не задумываясь о калориях. Coca-Cola Zero - отличный вкус без сахара и калорий!','',400,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vdsiob-uwa-uc-cornwht-OKO5lDffPoFEhK73rTOZ3.jpg',true,1,false,''),
('bar:napitki:fanta','bar','napitki','Напитки','Fanta','Fanta Апельсин – это классический безалкогольный напиток с легким фруктовым вкусом, содержащий 3% натурального апельсинового сока.','',400,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vdsiob-uwa-knhsikzxju-fSIc0mh-939Lnpz3RbCXW.jpg',true,2,false,''),
('bar:napitki:пепси','bar','napitki','Напитки','Пепси','','',380,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-vdsiob-uwa-nhilflevqs-yL6gEop8XHlz76DJXNmz5.jpg',true,3,false,''),
('bar:napitki:тоник','bar','napitki','Напитки','Тоник','','',350,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-vdsiob-uwa-jakzoubtaz-beigUqQYjzRt8GyRAHMgB.jpg',true,4,false,''),
('bar:napitki:dr-pepper','bar','napitki','Напитки','Dr Pepper','Освежающий безалкогольный сильногазированный пастеризованный напиток Dr Pepper Regular (Classic). Dr Pepper Classic представляет собой уникальное сочетание 23 различных оттенков вкуса (амаретто, миндаль, ежевика, чёрная солодка, морковь, гвоздика, вишня, карамель, кола, имбирь, можжевельник, лимон, патока, мускатный орех, апельсин, чернослив, слива, перец, ром, малина, помидоры, ваниль и секретный ингредиент производителя).','',400,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vdsiob-uwa-hdtpod-xyw-tjRIUeCk4C0IZAf9J018H.jpg',true,5,false,''),
('bar:napitki:red-bull','bar','napitki','Напитки','Red bull','Red Bull Energy Drink — безалкогольный энергетический газированный напиток. Энергетические напитки Red Bull содержат ингредиенты высокого качества: кофеин, таурин, витамины B, сахар и воду из альпийских регионов. В одной банке 250 мл содержится столько же кофеина, сколько в чашке кофе такого же объема.','',500,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vdsiob-uwa-ctxycxeiaj-4Mz_7j5QlRt64zQn691M0.jpg',true,6,false,''),
('bar:napitki:red-bull-sugarfree','bar','napitki','Напитки','Red bull sugarfree','Red Bull Sugarfree — безалкогольный тонизирующий газированный напиток без сахара.','',500,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vdsiob-uwa-rmyicokztj-OWNv_h-PyiQFiOyAB50Ff.jpg',true,7,false,''),
('bar:napitki:соки-swell','bar','napitki','Напитки','Соки Swell','Swell (Свелл) — это высококачественные соки и нектары, изготовленные по новейшим технологиям на современном европейском оборудовании, которое позволяет сохранять витамины и полезные вещества в готовом продукте.','',350,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vdsiob-uwa-a-vevanmfa-jBdOIzVKItzZMAI6cw_fp.jpg',true,8,false,''),
('bar:napitki:вода-без-газа','bar','napitki','Напитки','Вода без газа','Природная минеральная столовая вода обладает сбалансированным вкусом. Уникальный полноценный состав воды включает в себя микроэлементы и минералы, необходимые для поддержки здоровья. Вода Mever рекомендована для ежедневного употребления.','',350,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vdsiob-uwa-jhdqwoslzx-svyk1JJot-c7vAqgA6N6T.jpg',true,9,false,''),
('bar:napitki:вода-с-газом','bar','napitki','Напитки','Вода с газом','Borjomi — легендарная вода, которой больше 130 лет, ее знают и любят миллионы людей по всему миру. Она зарождается в вулканических глубинах Грузии в экологически чистой долине «Боржоми» и благодаря сочетанию полезных свойств вулканической воды и заряжающей силой минералов и микроэлементов Borjomi заботится о вашем здоровье, а узнаваемый с первого глотка вкус придает силы на новые свершения и идеи!','',500,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vdsiob-uwa-j-nojqhwzw-Tx5f2JS0F25H9fiP4r18e.jpg',true,10,false,''),
('bar:napitki:авторские-лимонады-ананас-лемонграсс-манго-маракуйя-ежевика-гранат-слива-рислинг-фейхоа-иланг-иланг','bar','napitki','Напитки','Авторские лимонады (Ананас-лемонграсс; манго-маракуйя; ежевика-гранат; слива-рислинг; фейхоа-иланг-иланг)','Лимонад - один из любимейших прохладительных напитков, вкус которого мы узнаём с детства.','',1000,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vdsiob-uwa-vsncndtncz-eHIjiV0Y3LX2vA7jUje_Q.jpg',true,11,false,''),
('bar:napitki:авторские-лимонады-0-4-ананас-лемонграсс-манго-маракуйя-ежевика-гранат-слива-рислинг-фейхоа-иланг-иланг','bar','napitki','Напитки','Авторские лимонады 0,4 (Ананас-лемонграсс; манго-маракуйя; ежевика-гранат; слива-рислинг; фейхоа-иланг-иланг)','','',550,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vdsiob-uwa-wtzk-rcgnz-aX1-ba97GEwmo4X_5H9Mc.jpg',true,12,false,''),
('bar:napitki:холодный-чай','bar','napitki','Напитки','Холодный чай','','',1000,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-vdsiob-uwa-rfihnvouxv-Rn08_IyuAm4SggBH4xSBy.jpg',true,13,false,''),
('bar:chaynaya-karta:молочный-улун-900мл','bar','chaynaya-karta','Чайная карта','Молочный улун 900мл','Молочный улун – один из самых популярных сортов улуна в мире. Его любят за яркий и легкий сливочный вкус, тонизирующий эффект и полезные для организма свойства','',800,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-tpzfbqwhfe-mxdn-vuuaq-X-1RMueEpHiRZBXsZBvVV.jpg',true,14,false,''),
('bar:chaynaya-karta:манговый-улун-900мл','bar','chaynaya-karta','Чайная карта','Манговый улун 900мл','','',800,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-tpzfbqwhfe-mth-upiiun-NOBlhvKTNN0thVTUtDRFy.jpg',true,15,false,''),
('bar:chaynaya-karta:жасминовый-900мл','bar','chaynaya-karta','Чайная карта','Жасминовый 900мл','','',800,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-tpzfbqwhfe-qhxdvnvlpd-a_yETTaKKjugARe1SGSlg.jpg',true,16,false,''),
('bar:chaynaya-karta:сенча-900мл','bar','chaynaya-karta','Чайная карта','Сенча 900мл','Сенча – классический китайский зеленый чай, обладающий сладковатым, чуть вяжущим вкусом и нежным свежим ароматом.','',800,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-tpzfbqwhfe-jheaatvkov-DH64DGY14IrApwySAKbE0.jpg',true,17,false,''),
('bar:chaynaya-karta:ассам-900мл','bar','chaynaya-karta','Чайная карта','Ассам 900мл','Ассам богат антиоксидантами, замедляющими процессы старения и предотвращающими развитие хронических заболеваний сердечно-сосудистой системы.','',800,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-tpzfbqwhfe-kxeivklqqe-8rlACWGrgroaOaLeoBeac.jpg',true,18,false,''),
('bar:chaynaya-karta:эрл-грей-900мл','bar','chaynaya-karta','Чайная карта','Эрл Грей 900мл','','',800,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-tpzfbqwhfe-ncrrjydjuv-RaZVXFN1bIwT1CInNfl3Q.jpg',true,19,false,''),
('bar:chaynaya-karta:наглый-фрукт-900мл','bar','chaynaya-karta','Чайная карта','Наглый фрукт 900мл','Насыщенный дерзкий вкус, ярко-фруктовый, кисловатый, с горчинкой.','',800,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-tpzfbqwhfe-n-bkxhcj-x-VPXunavCFrPd2dGkqpqPq.jpg',true,20,false,''),
('bar:chaynaya-karta:здоровый-сон-490мл','bar','chaynaya-karta','Чайная карта','Здоровый сон 490мл','Напиток чайный Здоровый сон – вкусный и полезный напиток, который поможет вам расслабиться, забыть о насущных проблемах и подготовиться ко сну.','',800,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-tpzfbqwhfe-zzweqbyzsh-rGhCGciZfrUUapkT-SoGE.jpg',true,21,false,''),
('bar:chaynaya-karta:пуэр-900мл','bar','chaynaya-karta','Чайная карта','Пуэр 900мл','Пуэр — уникальный постферментированный чай, выращенный в провинции Юннань, Китай.','',800,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-tpzfbqwhfe--pcotmbyjw-pEE8S1VTgenP1jE1xgcmH.jpg',true,22,false,''),
('bar:kitayskie-chai:пуэр-вишня-корица','bar','kitayskie-chai','Китайские чаи','Пуэр вишня-корица','Пуэр с добавлением ягод вишни и корицы. На первый план выходит вишневый вкус с легким послевкусием корицы.','',1100,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-pvziqcwwmg-jbiuwfysgf-7dxoMoOhUC9GStTIdlI35.jpg',true,23,false,''),
('bar:kitayskie-chai:шу-пуэр-гун-тин','bar','kitayskie-chai','Китайские чаи','Шу пуэр Гун Тин','Этот шу пуэр из уезда Мэнхай изготовлен из кустового сырья 2017 года, что наделило его зрелым и сбалансированным характером. Его аромат сдержанный и тёплый, с пряными и ореховыми нотами. Во вкусе мягкая ореховая основа гармонично переплетается с лёгкими оттенками сушёных ягод, а финал оставляет приятное, бархатисто-сладковатое послевкусие.','',1100,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-pvziqcwwmg-z-mjqcqqjo-xJayrGllPHNSvHqJTGe0X.jpg',true,24,false,''),
('bar:kitayskie-chai:бай-хао-инь-чжень','bar','kitayskie-chai','Китайские чаи','Бай Хао Инь Чжень','Данный белый чай, как и прочие белые чаи, не подвергается никакой обработке. Его аккуратно собирают вручную, не скручивают, не подвергают ферментации, а просто слегка подсушивают при помощи солнечных лучей. Можно сказать, что белый чай Бай Хао Инь Чжэнь – природный продукт, в котором сохраняется вся польза, все витамины и микроэлементы. Считается, что Бай Хао Инь Чжэнь – напиток, который помогает поддерживать здоровье и красоту.','',1100,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-pvziqcwwmg-exkjoskdzj-sPIgVK6oT6jgolewd3Pbg.jpg',true,25,false,''),
('bar:kitayskie-chai:бай-му-дань','bar','kitayskie-chai','Китайские чаи','Бай Му Дань','Китайский белый чай уезда Фудин, провинции Фуцзянь. Его начали производить с 1960-х годов, в настоящее время его делают, в основном, в уезде Чжэньхэ, Цзяньян, Фудин и Сунси. Чайный лист Бай Му Дань очень похож на листья пиона, благодаря чему заслужил свое название «Белый пион».','',1100,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-pvziqcwwmg-jjvfsxeedo-tyb3gsrumFRcWvs_0AkOD.jpg',true,26,false,''),
('bar:kitayskie-chai:ганпаудер','bar','kitayskie-chai','Китайские чаи','Ганпаудер','Ганпаудер — знаменитый китайский чай, который в Китае называют Люй Чжу, то есть «зелёная жемчужина». Чайный лист скручивают в маленькие шарики, которые становятся похожими на порох. Из-за внешнего вида этот чай также называют gunpowder, что с английского переводится как «порох».','',1100,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-pvziqcwwmg-mbylx--dtk-UwPm7EkqdLnATQdWI9Iwe.jpg',true,27,false,''),
('bar:kitayskie-chai:мао-фен','bar','kitayskie-chai','Китайские чаи','Мао Фен','Не только название скрутки листа, но и способ производства чая, при котором отбираются почки и прилегающие к ним два листа одинаковой длины. Такой чай отличается сбалансированным и богатым вкусом.','',1100,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-pvziqcwwmg-dnjmie-zur-Jb5VD0NoBSojlE5R3zNmc.jpg',true,28,false,''),
('bar:kitayskie-chai:те-гуань-инь','bar','kitayskie-chai','Китайские чаи','Те Гуань Инь','Вкус этого чая свежий, с легкой сладостью и характерным для улунов привкусом талого снега. Чайный напиток обладает ярким цветочным ароматом с нотами спелых яблок. Цвет настоя светло-желтый, прозрачный, который при последующих завариваниях становится зеленоватым.','',1100,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-pvziqcwwmg-njqm-s-oy--RKEbfmWfWFIoTQJGwUGvB.jpg',true,29,false,''),
('bar:kitayskie-chai:да-хун-пао','bar','kitayskie-chai','Китайские чаи','Да Хун Пао','Вкусовые свойства Да Хун Пао будут отличаться с каждым последующим чаепитием. Это многогранный чай, который с каждым проливом раскрывается по-новому. Многим кажется, что во время чаепития с Да Хун Пао, они успевают попробовать сразу несколько сортов чая. У него мягкое и бархатистое послевкусие, а еще легкая терпкость, которая со временем становится сладко-фруктовой.','',1100,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-pvziqcwwmg--v-gzkg--e-NriLH2Kr3bXSYM6-vQMXW.jpg',true,30,false,''),
('bar:kitayskie-chai:габа-фермерская','bar','kitayskie-chai','Китайские чаи','Габа Фермерская','Уникальный чай с тайваньских фермерских чайных садов. Отличается особенным, своеобразным вкусом и ярким цветочным ароматом. Чай Габа Фермерская легко пьется и порадует ценителей мягким, при этом насыщенным вкусом с тонкими хлебными, сладковатыми и чуть кислыми нотками.','',1100,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-pvziqcwwmg-oxgyrsjiim-MJSYWEu6OG-fkpOT4y0Rl.jpg',true,31,false,''),
('bar:dobavki-k-chayu:лимон','bar','dobavki-k-chayu','Добавки к чаю','Лимон','','',150,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vgejqoyhou-iybdegirxs-3sEuKlzbmw6EbBwrKEeLp.jpg',true,32,false,''),
('bar:dobavki-k-chayu:мята','bar','dobavki-k-chayu','Добавки к чаю','Мята','','',150,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vgejqoyhou-glpe-vzjvz-I0V5jIIbmY-p9GWFeGCm0.jpg',true,33,false,''),
('bar:dobavki-k-chayu:чабрец','bar','dobavki-k-chayu','Добавки к чаю','Чабрец','','',150,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vgejqoyhou-pyipykylgy-T7s-xWPGPgLIzNlxH97lG.jpg',true,34,false,''),
('bar:dobavki-k-chayu:м-д','bar','dobavki-k-chayu','Добавки к чаю','Мёд','','',150,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-vgejqoyhou-fxoqs-gurk-gfUv45Ti5dwfQm_C4Q_8Z.jpg',true,35,false,''),
('bar:nechaynyy-chay:манго-маракуйя','bar','nechaynyy-chay','Нечайный чай','Манго-маракуйя','Крафтовый чай с приятным освежающим вкусом, дополненный непревзойденным ароматом тропических фруктов.','',900,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-bjhbvwhhq--vypdtrsdww-Zd_yMI-2sN85MVpV1pSzx.jpg',true,36,false,''),
('bar:nechaynyy-chay:малина-черная-смородина','bar','nechaynyy-chay','Нечайный чай','Малина - черная смородина','Один из лучших согревающих миксов с полезными свойствами.','',900,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-bjhbvwhhq--xvqsozmapn-8fC6B66FaRPxu3ByapP-e.jpg',true,37,false,''),
('bar:nechaynyy-chay:цитрусовый','bar','nechaynyy-chay','Нечайный чай','Цитрусовый','Ароматный цитрусовый чай – безупречное решение для любого времени года.','',900,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-bjhbvwhhq--ddylysrofw-VM-L_izeyFHBgYJGTMuYZ.jpg',true,38,false,''),
('bar:nechaynyy-chay:персиковый','bar','nechaynyy-chay','Нечайный чай','Персиковый','Чай который очень полюбили наши гости.','',900,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-bjhbvwhhq--coxaivh-qx-O2ktuq-2NHTo9kZdmRPkS.jpg',true,39,false,''),
('bar:nechaynyy-chay:облепиховый','bar','nechaynyy-chay','Нечайный чай','Облепиховый','Облепиховый чай - настоящая находка для уставшего, испытывающего недостаток витаминов организма.','',900,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-bjhbvwhhq--mpgpdtgitf-jLoQx_vHSUd-ymec1JAvA.jpg',true,40,false,''),
('bar:nechaynyy-chay:инжир-чабрец-900мл','bar','nechaynyy-chay','Нечайный чай','Инжир-Чабрец 900мл','','',900,'https://foodeon.com/img/shared/product-placeholder-image.png',true,41,false,''),
('bar:nechaynyy-chay:черемуха-кардамон-900мл','bar','nechaynyy-chay','Нечайный чай','Черемуха-Кардамон 900мл','','',900,'https://foodeon.com/img/shared/product-placeholder-image.png',true,42,false,''),
('bar:nechaynyy-chay:малина-пан-900мл','bar','nechaynyy-chay','Нечайный чай','Малина-Пан 900мл','','',900,'https://foodeon.com/img/shared/product-placeholder-image.png',true,43,false,''),
('bar:kofe:эспрессо','bar','kofe','Кофе','Эспрессо','Эспрессо – это, действительно, прекрасный способ оживить унылый день.','',300,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-jlabxgucjm-jwa-tuemaf-de1Qjpgg1dORyVEM6V-75.jpg',true,44,false,''),
('bar:kofe:американо','bar','kofe','Кофе','Американо','Американо - кофе эспрессо, дополнительно разбавленный водой.','',300,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-jlabxgucjm-pomutgxcxp-wsuWMCvr01YJiOChaPc5_.jpg',true,45,false,''),
('bar:kofe:капучино','bar','kofe','Кофе','Капучино','','',400,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-jlabxgucjm-vuquiigh-m-2fvk_BHzyZrPo73DZ5Myn.jpg',true,46,false,''),
('bar:kofe:латте','bar','kofe','Кофе','Латте','','',400,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-jlabxgucjm-tlvzhinhpd-C0dnOD6XjQQbjJqKN-QOJ.jpg',true,47,false,''),
('bar:kofe:раф','bar','kofe','Кофе','Раф','','',500,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-jlabxgucjm-cirjagcbvw-16S06KDiYCORivhQUJwNI.jpg',true,48,false,''),
('bar:pivo-i-sidr:hofbrau','bar','pivo-i-sidr','Пиво и сидр','Hofbrau','Hofbräu — это натуральный продукт, который готовится в соответствии с "Законом о чистоте пива" 1516 года. Производитель пристально следит за качеством сырья и за процессом его использования. Каждый из четырех компонентов пенного напитка имеет особое значение в его производстве.','',850,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-uhomlq-uur-kyutnhhiih-d3Krx9mizqzQBg25Mh-hQ.jpg',true,49,false,''),
('bar:pivo-i-sidr:weihenstephan','bar','pivo-i-sidr','Пиво и сидр','Weihenstephan','','',850,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-uhomlq-uur-hrzsullgal-E3aT6LCXa1hrvGVP9V_CO.jpg',true,50,false,''),
('bar:pivo-i-sidr:guinness','bar','pivo-i-sidr','Пиво и сидр','Guinness','Пиво Guinness обладает солодовой сладостью и хмелевой горечью с нотками кофе и шоколада.','',850,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-uhomlq-uur-uqnragypsf-onPdpnDXjhHVX_oG1fPGl.jpg',true,51,false,''),
('bar:pivo-i-sidr:циндао','bar','pivo-i-sidr','Пиво и сидр','Циндао','','',500,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-uhomlq-uur-nwgsdfifbu-V9puGAdATpwd5cv_yOVUV.jpg',true,52,false,''),
('bar:pivo-i-sidr:paulaner','bar','pivo-i-sidr','Пиво и сидр','Paulaner','Это мягкое золотистое пиво, имеющее приятный солодовый вкус с тонкими нотками хмеля. Полнотелое, янтарного цвета, приготовленное методом низового брожения.','',850,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-uhomlq-uur-kpgzutapfx-xnUbausXShAVbalLlCtDd.jpg',true,53,false,''),
('bar:pivo-i-sidr:spaten','bar','pivo-i-sidr','Пиво и сидр','Spaten','Пиво Шпатен отличается образцовым золотистым цветом, а при наливании дает идеально белую бархатистую пенную шапку. В аромате напитка хорошо ощущается хмель и солод, которые дополнены штрихами луговой травы.','',800,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-uhomlq-uur-nawhirmlfq-EvnIBigLP8LFuJc6h48X9.jpg',true,54,false,''),
('bar:pivo-i-sidr:corona-extra','bar','pivo-i-sidr','Пиво и сидр','Corona Extra','"Корона Экстра" — напиток с элегантным, освежающим вкусом, в котором раскрываются нотки солода, молодой кукурузы и лайма.','',650,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-uhomlq-uur-lqhosurygu-88gTAQxP3bNvUjyiGYV-K.jpg',true,55,false,''),
('bar:pivo-i-sidr:leffe-светлое','bar','pivo-i-sidr','Пиво и сидр','Leffe светлое','','',650,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-uhomlq-uur-vtagvcodsd-O-UZWH96q-FpDvU79eoJ_.jpg',true,56,false,''),
('bar:pivo-i-sidr:leffe-темное','bar','pivo-i-sidr','Пиво и сидр','Leffe темное','','',650,null,true,57,false,''),
('bar:pivo-i-sidr:clausthaller','bar','pivo-i-sidr','Пиво и сидр','Clausthaller','Clausthaler (Клаусталер) - премиальное безалкогольное пиво из Германии, обладающее безупречным вкусом и высочайшим качеством.','',650,null,true,58,false,''),
('bar:pivo-i-sidr:hoegarden','bar','pivo-i-sidr','Пиво и сидр','Hoegarden','Хугарден (Hoegaarden) — название нефильтрованного пшеничного, то есть белого пива, которое производят в небольшой бельгийской деревеньке.','',450,null,true,59,false,''),
('bar:pivo-i-sidr:stella-artois','bar','pivo-i-sidr','Пиво и сидр','Stella Artois','Stella Artois - суперпремиальный классический лагер с особым горьковатым вкусом и освежающим хмелевым послевкусием.','',500,null,true,60,false,''),
('bar:pivo-i-sidr:сидр-0-5-в-ассортименте','bar','pivo-i-sidr','Пиво и сидр','Сидр 0,5 в ассортименте','Полусухой сидр. Обладает приятным, освежающим вкусом с яркими нотками зеленого яблока и бодрящей фруктовой кислинкой.','',500,null,true,61,false,''),
('bar:pivo-i-sidr:сидр-la-bolee-bretonne-brut-0-7','bar','pivo-i-sidr','Пиво и сидр','Сидр La Bolee Bretonne Brut 0,7','','',1500,null,true,62,false,''),
('bar:beloe-vino:совиньон-блан-125-мл-юар','bar','beloe-vino','Белое вино','Совиньон Блан 125 мл. ЮАР','','',650,null,true,63,false,''),
('bar:beloe-vino:пино-гриджио-125-мл-италия','bar','beloe-vino','Белое вино','Пино Гриджио 125 мл. Италия','','',650,null,true,64,false,''),
('bar:beloe-vino:рислинг-125-мл-германия','bar','beloe-vino','Белое вино','Рислинг 125 мл. Германия','','',700,null,true,65,false,''),
('bar:beloe-vino:преферер-125-мл','bar','beloe-vino','Белое вино','Преферер 125 мл.','','',800,null,true,66,false,''),
('bar:beloe-vino:совиньон-блан-0-75-юар','bar','beloe-vino','Белое вино','Совиньон Блан 0,75 ЮАР','','',3900,null,true,67,false,''),
('bar:beloe-vino:пино-гриджио-0-75-италия','bar','beloe-vino','Белое вино','Пино Гриджио 0,75 Италия','','',3900,null,true,68,false,''),
('bar:beloe-vino:рислинг-0-75-германия','bar','beloe-vino','Белое вино','Рислинг 0,75 Германия','','',4200,null,true,69,false,''),
('bar:beloe-vino:преферер-750-мл','bar','beloe-vino','Белое вино','Преферер 750 мл.','','',4800,null,true,70,false,''),
('bar:krasnoe-vino:каберне-совиньон-125-мл-юар','bar','krasnoe-vino','Красное вино','Каберне Совиньон 125 мл. ЮАР','','',600,null,true,71,false,''),
('bar:krasnoe-vino:кьянти-125-мл-италия','bar','krasnoe-vino','Красное вино','Кьянти 125 мл. Италия','','',700,null,true,72,false,''),
('bar:krasnoe-vino:мальбек-125-мл-аргентина','bar','krasnoe-vino','Красное вино','Мальбек 125 мл. Аргентина','','',700,null,true,73,false,''),
('bar:krasnoe-vino:каберне-совиньон-0-75-юар','bar','krasnoe-vino','Красное вино','Каберне Совиньон 0,75 ЮАР','','',3600,null,true,74,false,''),
('bar:krasnoe-vino:кьянти-0-75-италия','bar','krasnoe-vino','Красное вино','Кьянти 0,75 Италия','','',4200,null,true,75,false,''),
('bar:krasnoe-vino:мальбек-0-75-аргентина','bar','krasnoe-vino','Красное вино','Мальбек 0,75 Аргентина','','',4200,null,true,76,false,''),
('bar:igristye-vina:шато-тамань-125-мл-россия','bar','igristye-vina','Игристые вина','Шато Тамань 125 мл. Россия','','',400,null,true,77,false,''),
('bar:igristye-vina:проссекко-125-мл-италия','bar','igristye-vina','Игристые вина','Проссекко 125 мл. Италия','','',700,null,true,78,false,''),
('bar:igristye-vina:шато-тамань-0-75-россия','bar','igristye-vina','Игристые вина','Шато Тамань 0,75 Россия','','',2400,null,true,79,false,''),
('bar:igristye-vina:проссекко-0-75-италия','bar','igristye-vina','Игристые вина','Проссекко 0,75 Италия','','',4200,null,true,80,false,''),
('bar:igristye-vina:асти-0-75-италия','bar','igristye-vina','Игристые вина','Асти 0,75 Италия','','',4200,null,true,81,false,''),
('bar:igristye-vina:мартини-асти-750-мл','bar','igristye-vina','Игристые вина','Мартини Асти 750 мл.','','',4900,null,true,82,false,''),
('bar:viski:гленгэрри-50-мл','bar','viski','Виски','Гленгэрри 50 мл.','','',550,null,true,83,false,''),
('bar:viski:баллантайнс-50мл','bar','viski','Виски','Баллантайнс 50мл.','','',550,null,true,84,false,''),
('bar:viski:дюарс-50-мл','bar','viski','Виски','Дюарс 50 мл.','','',600,null,true,85,false,''),
('bar:viski:бушмилз-50-мл','bar','viski','Виски','Бушмилз 50 мл.','','',550,null,true,86,false,''),
('bar:viski:джек-дэниелс-50-мл','bar','viski','Виски','Джек Дэниелс 50 мл.','','',690,null,true,87,false,''),
('bar:viski:чивас-ригал-12-50-мл','bar','viski','Виски','Чивас Ригал 12 50 мл.','','',700,null,true,88,false,''),
('bar:viski:джемессон-50мл','bar','viski','Виски','Джемессон 50мл.','','',600,null,true,89,false,''),
('bar:viski:джим-бим-50мл','bar','viski','Виски','Джим Бим 50мл.','','',500,null,true,90,false,''),
('bar:vodka:мамонт-50-мл','bar','vodka','Водка','Мамонт 50 мл','','',400,null,true,91,false,''),
('bar:vodka:финляндия-50-мл','bar','vodka','Водка','Финляндия 50 мл.','','',450,null,true,92,false,''),
('bar:nastoyki:онегин-вишня-50-мл','bar','nastoyki','Настойки','Онегин Вишня 50 мл.','','',400,null,true,93,false,''),
('bar:nastoyki:онегин-курага-50-мл','bar','nastoyki','Настойки','Онегин Курага 50 мл.','','',400,null,true,94,false,''),
('bar:nastoyki:онегин-грейпфрут-50-мл','bar','nastoyki','Настойки','Онегин грейпфрут 50 мл.','','',400,null,true,95,false,''),
('bar:nastoyki:онегин-черная-смородина-50-мл','bar','nastoyki','Настойки','Онегин черная смородина 50 мл.','','',400,null,true,96,false,''),
('bar:nastoyki:онегин-черноплодная-рябина-50-мл','bar','nastoyki','Настойки','Онегин черноплодная рябина 50 мл.','','',400,null,true,97,false,''),
('bar:dzhin:би-джин-50-мл','bar','dzhin','Джин','Би Джин 50 мл.','','',400,null,true,98,false,''),
('bar:dzhin:босфорд-50-мл','bar','dzhin','Джин','Босфорд 50 мл.','','',450,null,true,99,false,''),
('bar:dzhin:бифитер-50-мл','bar','dzhin','Джин','Бифитер 50 мл.','','',600,null,true,100,false,''),
('bar:dzhin:бомбей-сапфир-50-мл','bar','dzhin','Джин','Бомбей Сапфир 50 мл.','','',800,null,true,101,false,''),
('bar:dzhin:норминдия-50-мл','bar','dzhin','Джин','Норминдия 50 мл.','','',500,null,true,102,false,''),
('bar:rom:такамака-бланк-50-мл','bar','rom','Ром','Такамака Бланк 50 мл.','','',500,null,true,103,false,''),
('bar:rom:такамака-дарк-50-мл','bar','rom','Ром','Такамака Дарк 50 мл.','','',500,null,true,104,false,''),
('bar:rom:капитан-морган-темный-50-мл','bar','rom','Ром','Капитан Морган темный 50 мл.','','',550,null,true,105,false,''),
('bar:rom:оакхарт-50-мл','bar','rom','Ром','Оакхарт 50 мл.','','',700,null,true,106,false,''),
('bar:konyak:арарат-3-50-мл','bar','konyak','Коньяк','Арарат 3* 50 мл.','','',400,null,true,107,false,''),
('bar:konyak:хеннесси-vs-50-мл','bar','konyak','Коньяк','Хеннесси VS 50 мл.','','',950,null,true,108,false,''),
('bar:tekila:кампо-азул-50-мл','bar','tekila','Текила','Кампо Азул 50 мл.','','',550,null,true,109,false,''),
('bar:tekila:де-лос-дорадос-50-мл','bar','tekila','Текила','Де Лос Дорадос 50 мл.','','',600,null,true,110,false,''),
('bar:tekila:хосе-куэрво-50-мл','bar','tekila','Текила','Хосе Куэрво 50 мл.','','',600,null,true,111,false,''),
('bar:bitter:фернет-бранка-50-мл','bar','bitter','Биттер','Фернет-Бранка 50 мл.','','',500,null,true,112,false,''),
('bar:bitter:ягермайстер-50-мл','bar','bitter','Биттер','Ягермайстер  50 мл.','','',600,null,true,113,false,''),
('bar:vermut:мартини-россо-50-мл','bar','vermut','Вермут','Мартини Россо 50 мл.','','',450,null,true,114,false,''),
('bar:vermut:мартини-фиеро-50-мл','bar','vermut','Вермут','Мартини Фиеро 50 мл.','','',450,null,true,115,false,''),
('bar:kokteyli:лимончелло','bar','kokteyli','Коктейли','Лимончелло','','',400,null,true,116,false,''),
('bar:kokteyli:мохито','bar','kokteyli','Коктейли','Мохито','','',800,null,true,117,false,''),
('bar:kokteyli:мартини-фиеро-тоник','bar','kokteyli','Коктейли','Мартини Фиеро - Тоник','','',990,null,true,118,false,''),
('bar:kokteyli:май-тай','bar','kokteyli','Коктейли','Май Тай','','',800,null,true,119,false,''),
('bar:kokteyli:негрони','bar','kokteyli','Коктейли','Негрони','','',800,null,true,120,false,''),
('bar:kokteyli:лонг-айленд','bar','kokteyli','Коктейли','Лонг Айленд','','',1100,null,true,121,false,''),
('bar:kokteyli:апероль-спритц','bar','kokteyli','Коктейли','Апероль Спритц','','',990,null,true,122,false,''),
('bar:kokteyli:глинтвейн','bar','kokteyli','Коктейли','Глинтвейн','','',800,null,true,123,false,''),
('bar:kokteyli:беллини','bar','kokteyli','Коктейли','Беллини','','',800,null,true,124,false,''),
('bar:kokteyli:россини','bar','kokteyli','Коктейли','Россини','','',800,null,true,125,false,''),
('bar:zakuski:вяленое-мясо-курицы','bar','zakuski','Закуски','Вяленое мясо курицы','','',500,null,true,126,false,''),
('bar:zakuski:вяленое-мясо-говядина','bar','zakuski','Закуски','Вяленое мясо говядина','','',550,null,true,127,false,''),
('bar:zakuski:вяленое-мясо-ассорти-3-вида','bar','zakuski','Закуски','Вяленое мясо ассорти 3 вида','','',1300,null,true,128,false,''),
('bar:zakuski:фисташки','bar','zakuski','Закуски','Фисташки','','',500,null,true,129,false,''),
('bar:zakuski:арахис','bar','zakuski','Закуски','Арахис','','',350,null,true,130,false,''),
('bar:zakuski:начос','bar','zakuski','Закуски','Начос','','',300,null,true,131,false,''),
('bar:zakuski:соус-в-ассортименте','bar','zakuski','Закуски','Соус в ассортименте','','',150,null,true,132,false,''),
('bar:pitstsa:мясная','bar','pitstsa','Пицца','Мясная','','',1000,null,true,133,false,''),
('bar:pitstsa:ветчина-и-грибы','bar','pitstsa','Пицца','Ветчина и грибы','','',1000,null,true,134,false,''),
('bar:pitstsa:пепперони','bar','pitstsa','Пицца','Пепперони','','',1000,null,true,135,false,''),
('bar:pitstsa:четыре-сыра','bar','pitstsa','Пицца','Четыре сыра','','',1000,null,true,136,false,''),
('bar:deserty:мороженое','bar','deserty','Десерты','Мороженое','','',350,null,true,137,false,''),
('bar:deserty:печенье','bar','deserty','Десерты','Печенье','','',350,null,true,138,false,''),
('bar:deserty:шоколадки','bar','deserty','Десерты','Шоколадки','','',250,null,true,139,false,''),
('bar:dopolnitelnye-uslugi:аренда-playstation-4-на-1-час','bar','dopolnitelnye-uslugi','Дополнительные услуги','Аренда Playstation 4 на 1 час','','',200,null,true,140,false,''),
('bar:dopolnitelnye-uslugi:аренда-playstation-5-на-1-час','bar','dopolnitelnye-uslugi','Дополнительные услуги','Аренда Playstation 5 на 1 час','','',300,null,true,141,false,''),
('hookah:hookah:классический','hookah','hookah','Кальяны','Классический','Кальяны на глиняной чаше – классика жанра','',2500,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-an-etokblg-gvbbmrclxq-pntSiWktlAX6AoFpXJYkN.jpg',true,142,false,''),
('hookah:hookah:авторский','hookah','hookah','Кальяны','Авторский','Авторские миксы наших кальянных мастеров с использованием табаков премиум качества','',3000,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-an-etokblg-qhjdasev-j-trA2cxasrFg7XfHC8FuLZ.jpg',true,143,false,''),
('hookah:hookah:эксклюзивный-кальян','hookah','hookah','Кальяны','Эксклюзивный кальян','Используются табаки лимитированных серий, которые не встретишь в продаже','',3500,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-an-etokblg-kqnfrpfchc-ZSBwyHX_5xexheCkgsqwn.jpg',true,144,false,''),
('hookah:hookah:кальян-парфюм','hookah','hookah','Кальяны','Кальян ПАРФЮМ','','',3500,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-an-etokblg-chzelpi-ay-lix-rh3gauTkwPDGlYSJs.jpg',true,145,false,''),
('hookah:hookah:электронная-чаша','hookah','hookah','Кальяны','Электронная чаша','','',3500,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-an-etokblg-porpa-iyhv-QLaXjd3jQtM6pDyuGIMSF.jpg',true,146,false,''),
('hookah:hookah:кальян-на-сигарном-листе','hookah','hookah','Кальяны','Кальян на сигарном листе','','',3600,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-an-etokblg-hyhjoivhuj-4xJ3aV9tDrXQRZ0n0UvNP.jpg',true,147,false,''),
('hookah:hookah:на-грейпфруте','hookah','hookah','Кальяны','На грейпфруте','Яркий аромат грейпфрута придает табаку изысканную терпкость и создает оригинальное сладко-свежее послевкусие.','',3600,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-an-etokblg-qzkfdceoqn-GsdigAZkQqLhrjglPNXBE.jpg',true,148,false,''),
('hookah:hookah:кальян-на-ананасе','hookah','hookah','Кальяны','Кальян на ананасе','','',3900,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-an-etokblg-hmribcdyjm-Zu8yVS3JKWCeQp_kE4cli.jpg',true,149,false,''),
('hookah:hookah:кальян-на-гранате','hookah','hookah','Кальяны','Кальян на гранате','','',3900,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-an-etokblg-dcjuwfyour-PSlxhRd8af0re4kTw9yoU.jpg',true,150,false,''),
('hookah:hookah:кальян-на-помело-кактус-питахайя','hookah','hookah','Кальяны','Кальян на помело\кактус\питахайя','','',5000,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-an-etokblg-lmquyqjavg-xpkQ81uUk3OKrjFrHLrRu.jpg',true,151,false,''),
('hookah:hookah:кальян-авторский','hookah','hookah','Кальяны','Кальян Авторский','','',5500,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-an-etokblg--uozndlpao-CIwX6A9Se1bd_MhqQpN7n.jpg',true,152,false,''),
('hookah:hookah:добавка-премиум-табаков','hookah','hookah','Кальяны','Добавка премиум табаков','WTO TOBACCO Уникальный продукт для кальяна на основе дорогих сигарных табаков. Табак для кальяна производится по уникальной новой технологии — это экстрагирование вкуса и аромата сигарного листа в соус.','',500,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-gqxz-an-etokblg-lpmxrurwwy-YMXM5P2_toBF6_P0NLKO-.jpg',true,153,false,''),
('hookah:hookah:добавка-премиум-табаков-к-фруктовой-чаше','hookah','hookah','Кальяны','Добавка премиум табаков к фруктовой чаше','','',600,'https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-an-etokblg-rmpuwjqzlq-X4m0leR_ryu5CI4GJYX6N.jpg',true,154,false,'')
on conflict (item_key) do update set section_id=excluded.section_id,section_title=excluded.section_title,name=excluded.name,description=excluded.description,volume=excluded.volume,price=excluded.price,image_url=excluded.image_url,available=excluded.available,sort_order=excluded.sort_order,archived=excluded.archived,badge=excluded.badge;

insert into public.promotions(title,text,type_label,image_url,sort_order)
select * from (values
('НОВИНКА!!! Лимончелло','Специальное предложение — 400 ₽','Новинка','https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-uwmynprpyo-wpxujzktuh-Bh_9qj8rtFcW_vdm1CCck.jpg',10),
('Скидка 15% в твой день рождения','Подробности уточняйте у администратора.','Скидка','https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-uwmynprpyo-vnnfaexomr-p8mm2oDGBqtcHEMlyCZh_.jpg',20),
('Фиеро-тоник 1+1=3','Специальное предложение — 1980 ₽','Акция','https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-uwmynprpyo-tntypoi-fd--szlnxVfjuY2sNklirujR.jpg',30),
('Лонг айленд 1+1=3','Специальное предложение — 2200 ₽','Акция','https://static.foodeon.com/assets/uploaded-media/product-media/posidym-jutf-uwmynprpyo-whzrwcvdmk-31P2tRuPvCYjDdlB4ZgtY.jpg',40)
) v(title,text,type_label,image_url,sort_order)
where not exists(select 1 from public.promotions);

insert into public.rules(title,text,sort_order)
select * from (values
('Только 18+','При посещении заведения администратор вправе попросить документ, подтверждающий возраст.',10),
('Бронирование','Стол считается забронированным после подтверждения администратора. Для отдельных дат возможен депозит.',20),
('Время брони','При опоздании более чем на 15 минут бронь может быть отменена, если вы не предупредили администратора.',30),
('Поведение гостей','Просим бережно относиться к имуществу заведения и уважительно общаться с другими гостями и персоналом.',40),
('Кальянная подача','Для комфортного отдыха действует минимальное количество кальянов на компанию: для 1–3 гостей — 1 кальян, для 3–5 гостей — 2 кальяна, для компаний от 5 гостей — 3 кальяна. Стандартное время курения одного кальяна составляет до 2 часов.',50)
) v(title,text,sort_order)
where not exists(select 1 from public.rules);
